const pathname = {
  home: '/',
  about: '/about',
  services: '/services',
  webServices: '/web-services',
  productService: '/product-services',
  digitalService: '/digital-services',
  appService: '/app-services',
  contact: '/contact',
  freeAudit: '/freeAudit',
  signup: '/signup',
  signUp: '/sign-up',
  login: '/login',
  planandprice: '/plan&price',
  planPrice: '/plan-price',
  comingsoon: '/comingsoon',
  oopsError: '/oopsError',
  forgetPassword: '/forget-password',
  massageSubmition: '/massage-submition',
  auditReqSubmition: '/audit-submition',
  termsConditions: '/terms-conditions',
  privacyPolicy: '/privacy-policy',
  blogs: '/blogs',
  singleBlog: '/single-blog',
  notFound: '*',
};
export default pathname;
